##########################################
## User modifiable configuration options #
##########################################

# Set the number of availables cores for the analysis.

available_cores: 7

# List the FASTQ files containing the data. Note that the files must have the extesion ".FASTQ", i.e., "sample_1.FASTQ".

fastq:
    [
    "915800",
    "915824",
    "915871",
    "916197",
    "916199",
    "916201",
    "915812",
    "915836",
    "915882",
    "916198",
    "916200",
    "916202",
    "915848",
    "915860",
    "915883",
    "916203",
    "916204",
    "916205"
    ]

# List each FASTQ file (must match the above list) and the common name of the sample. The common name will be used to identify the replicates during the differential expression analysis. The format needs to folow the example below, where all samples are listed in a string and each sample is separated by commas. Use "-" to separate FASTQ file ID from the common name and do not use "-" as part of the sample name.

Grouping_var: "915871-adult_leaf,915800-adult_leaf,915824-adult_leaf,916197-adult_leaf,916199-adult_leaf,916201-adult_leaf,915882-juvenile_leaf,915812-juvenile_leaf,915836-juvenile_leaf,916198-juvenile_leaf,916200-juvenile_leaf,916202-juvenile_leaf,915883-xylem,915848-xylem,915860-xylem,916203-xylem,916204-xylem,916205-xylem"

# From the files listed above, enumarate those produced by the libraries containing the methylation-INSENSITIVE restriction enzyme (i.e, MspI). Must be a string of FASTQ IDs separated by commas.

samples_from_ms_insenstive: "916197,916199,916201,916198,916200,916202,916203,916204,916205"

# Full path to reference genome. The reference genome must be in the FASTA format and ended with the extension ".fa", i.e., "genome.fa". The reference genome is expected to be softmasked to mark repetitive elements.

reference_genome: "Egrandis_297_v2.0.softmasked.fa"

# Files containing the barcodes per sample used by DArT during the library preparation. Those files should be provided by the company and are used by trimmomatic to identify and remove barcodes that may be part of the sequencing reads.

barcodes_files: 
    [
    "barcodes_C9C2CANXX_2.txt",
    "barcodes_C9C2CANXX_8.txt"
    ]

# Sequence of Illummina adapters used during the library preparation in the FASTA format and ended with the extension ".fa", i.e., "adapters.fa". This file is used by trimmomatic to identify and remove adaptors that may be part of the sequencing reads.

adapters_file: adapters.fa

# Sequence of the restriction site of each restriction enzyme in the FASTA format and ended with the extension ".fa", i.e., "restriction_sites.fa"
restriction_site_sequences: "mspI_pstI_sites.fa"

########################################
## Options that should not be altered ## 
########################################

combining_samples: "all_samples_without_barcodes_and_adapters.fq"
combine_bam: all_samples.bam

mapping:
    fastq:
        [
    "no_mapped_mm0",
    "no_mapped_mm1",
    "no_mapped_mm2",
    "no_mapped_mm3"
        ]
    sam:
        [
    "all_reads_mm0",
    "all_reads_mm1",
    "all_reads_mm2",
    "all_reads_mm3"
        ]
    sam_samples:
        [
    "_mm0",
    "_mm1",
    "_mm2",
    "_mm3"
        ]

bam_to_bed:
    bed_name: all_samples.bed

position_of_RE_sites: "enzymes_positions_of_RE_sites_sorted.bed"

defines_the_position_of_sampled_sites:
    [
    "enz_sites_sample_reads_clusters.bed",
    "enz_sites_sample_reads_clusters_of_interest.bed"
    ]

finds_unique_positions:
    [
    "good_clusters.bed",
    "clusters_without_pstI.bed",
    "msdartseq_positions.bed"
    ]

featurecounts:
    [
    "msdartseq_positions.saf",
    "msdartseq_counts"
    ]

counts_correction:
    [
    "msdartseq_positions_fixed.bed",
    "msdartseq_counts_fixed.tst"
    ]

marks_with_msp_outputs:
    [
    "marks_with_counts_bigger_than_0",
    ]

sampled_site_position:
    [
    "msdartseq_sequenced_fragments",
    "msdartseq_methylation_sites_of_sequenced_fragments",
    "ms_dartseq_counts"
    ]
  
find_methylation_site_position_outputs_p2:
    [
    "mspI_sites"
    ]

edgeR_with_DArTCounts_params:
    prefix: edgeR_results/edger_group
    min_msp: 3
    fdr: 0.05
    log_fold_change: 2

DEseq2_with_DArTCounts_params:
    prefix: DEseq2_results/deseq_group
    min_msp: 3
    fdr: 0.05
    log_fold_change: 2

edger_vs_deseq2_output:
    [
    "edger_DEseq2_consensus_DM_fragments.tst",
    "edger_DEseq2_consensus_methylated_sites.tst",
    "edgeR_vs_DEseq2_methylated_sites.svg"
    ]

generated_bed_file_of_DNA_methylations:
    [
    "methylated_sites.bed",
    "methylated_sites_only_plus.bed"
    ]

intersect_marks_params:
    prefix: ["sites_on_the_intersection/MS-DArT"]
    grupos_intersect: ["true_sites/MS-DArT_marks_with_counts_bigger_than_0.txt"]